spring:
  application.name: config-server
  #profiles:
    #激活本地配置
   # active: native
  cloud:
    config:
      server:
        #native:
          #指定配置文件的位置
          #searchLocations: file:F:/properties/
        git:
          uri: http://git.oschina.net/didispace/SpringBoot-Learning/
          searchPaths: Chapter9-1-4/config-repo
          username: username
          password: password
server:
  port: 4001